[package]
name = "logitech-led-sdk-sys"
version = "0.0.0"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
build = "build.rs"
license = "MIT / Apache-2.0"

[dependencies]

[build-dependencies]
bindgen = "0.58.1"